### ISSUE TITLE
Unable to install bhrcr package on RStudio

### ISSUE THREAD

**Issue by jeyamello** [cran/bhrcr#1]
Hi, I am having trouble installing the bhrcr package on R Studio. I attempted it with the latest and earlier versions of R (3.4.0, 3.5.0, 3.5.2, 3.5.3, 3.6.0, and etc.), with no success. How do I successfully install it? Thank you.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by jeyamello** [comment]
Ah, sorry, new to github. Thanks, I will do so. :)
